export default {
  START_OVER: 'START_OVER',
  PLAYER_ENTERED: 'PLAYER_ENTERED',
  ERROR_OCCURRED: 'ERROR_OCCURRED',
  PLAYER_SELECTED: 'PLAYER_SELECTED',
  PLAYER_FOUND: 'PLAYER_FOUND',
  NO_PLAYER_FOUND: 'NO_PLAYER_FOUND',
  MATCHES_FOUND: 'MATCHES_FOUND',
  MATCH_SELECTED: 'MATCH_SELECTED',
  MATCH_LOADED: 'MATCH_LOADED',
  PLAYER_MATCHES_CLICKED: 'PLAYER_MATCHES_CLICKED',
}
